"""Shared constants for AI-Ops platform."""

# ── Task Status ──────────────────────────────────────
TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_VALIDATING = "VALIDATING"
TASK_STATUS_UPLOADING = "UPLOADING"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_COLLECTING = "COLLECTING"
TASK_STATUS_SUCCESS = "SUCCESS"
TASK_STATUS_FAILED = "FAILED"
TASK_STATUS_CANCELLED = "CANCELLED"
TASK_STATUS_TIMEOUT = "TIMEOUT"

TERMINAL_STATUSES = {TASK_STATUS_SUCCESS, TASK_STATUS_FAILED, TASK_STATUS_CANCELLED, TASK_STATUS_TIMEOUT}
ACTIVE_STATUSES = {TASK_STATUS_PENDING, TASK_STATUS_VALIDATING, TASK_STATUS_UPLOADING, TASK_STATUS_RUNNING, TASK_STATUS_COLLECTING}

# ── Document Status ──────────────────────────────────
DOC_STATUS_UPLOADED = "UPLOADED"
DOC_STATUS_PARSING = "PARSING"
DOC_STATUS_READY = "READY"
DOC_STATUS_FAILED = "FAILED"

# ── Server Status ────────────────────────────────────
SERVER_STATUS_ACTIVE = "ACTIVE"
SERVER_STATUS_DISABLED = "DISABLED"
SERVER_STATUS_UNKNOWN = "UNKNOWN"
SERVER_STATUS_FAILED = "FAILED"

# ── Error Codes ──────────────────────────────────────
SUCCESS = 0
ERR_PARAM = 40001
ERR_UNAUTHORIZED = 40101
ERR_FORBIDDEN = 40301
ERR_NOT_FOUND = 40401
ERR_SYSTEM = 50001
ERR_SSH_CONNECT = 60001
ERR_SSH_DIR_NOT_ALLOWED = 60002
ERR_SSH_COMMAND_REJECTED = 60003
ERR_SSH_UPLOAD = 60004
ERR_SSH_DOWNLOAD = 60005
ERR_DEEPSEEK = 70001
ERR_KNOWLEDGE_SEARCH = 70002
ERR_FILE_FORMAT = 80001
ERR_FILE_TOO_LARGE = 80002

# ── User Roles ───────────────────────────────────────
ROLE_ADMIN = "admin"
ROLE_DEVELOPER = "developer"
ROLE_OPERATOR = "operator"
ROLE_VIEWER = "viewer"

# ── Apptainer ────────────────────────────────────────
DANGEROUS_DEF_PATTERNS = [
    "rm -rf /", "mkfs", "dd if=", "| bash",
    "chmod -R 777", "/etc/shadow", "useradd",
    "passwd", "visudo", "systemctl", "reboot", "shutdown",
]
