# Generated by Django 5.0.14 on 2026-06-17 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_scriptexecutiontask_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecutiontask',
            name='run_as',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ScriptParamPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('args', models.TextField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_presets', to='scripts.scriptfile')),
            ],
            options={
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['script', '-last_used_at'], name='idx_script_preset_used')],
                'unique_together': {('script', 'name')},
            },
        ),
    ]
