# Generated by Django 5.0.14 on 2026-06-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('knowledge_file', 'Knowledge File'), ('apptainer_def', 'Apptainer Definition'), ('build_log', 'Build Log'), ('sif_path_record', 'SIF Path Record'), ('benchmark_script', 'Benchmark Script'), ('benchmark_log', 'Benchmark Log'), ('benchmark_report', 'Benchmark Report'), ('script_log', 'Script Log'), ('script_output', 'Script Output')], max_length=64),
        ),
    ]
