# Generated by Django 5.0.14 on 2026-06-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(default=0)),
                ('mem_percent', models.FloatField(default=0)),
                ('mem_used_gb', models.FloatField(default=0)),
                ('mem_total_gb', models.FloatField(default=0)),
                ('gpu_percent', models.FloatField(default=0)),
                ('gpu_mem_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('disk_used_gb', models.FloatField(default=0)),
                ('disk_total_gb', models.FloatField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.server')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
