# Generated by Django 5.0.14 on 2026-06-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_store_credentials_plaintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='allow_script_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serveralloweddir',
            name='purpose',
            field=models.CharField(choices=[('build', 'Build'), ('benchmark', 'Benchmark'), ('script', 'Script'), ('report', 'Report'), ('general', 'General')], default='general', max_length=32),
        ),
    ]
